[pytest]
#cDJANGO_SETTINGS_MODULE = ourchive_app.settings
REST_FRAMEWORK = ourchive_app.api
# -- recommended but optional:
python_files = tests/*.py tests.py test_*.py *_tests.py
django_find_project = true
log_cli = true