[pytest]
python_paths = ourchive_app
DJANGO_SETTINGS_MODULE = ourchive_app.settings
#REST_FRAMEWORK = api
# -- recommended but optional:
python_files = tests/*.py test_*.py *_tests.py
django_find_project = false
log_cli = true