# Generated by Django 2.2.2 on 2019-06-11 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('curator_title', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('anon_comments_permitted', models.BooleanField(default=False)),
                ('comments_permitted', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='api.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Work')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_label', models.CharField(max_length=200)),
                ('send_email', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Chapter'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('route', models.CharField(max_length=200)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NotificationType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message_subject', models.CharField(max_length=200)),
                ('message_content', models.TextField()),
                ('message_read', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
                ('replies', models.ManyToManyField(related_name='_message_replies_+', to='api.Message')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recieved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkLink',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bookmark')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='bookmark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Bookmark'),
        ),
    ]
